name: Deploy to staging
on:
  push:
    branches: [main]

jobs:
  deploy_everything:
    runs-on: ubuntu-latest
    name: Deplying everything to staging
    steps:
      - name: SSH into server
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/ssh_key
          chmod 600 ~/ssh_key
          mkdir -p ~/.ssh
          echo "${{ secrets.KNOWN_HOST }}" > ~/.ssh/known_hosts
          ssh -i ~/ssh_key ubuntu@65.0.138.93
          cd week-25-ci-cd
          pnpm install
          pnpm run build
          pm2 restart all
